name: Check Markdown links

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tcort/github-action-markdown-link-check@v1
