name: Produce a stable download link for the slides
on:
  push:
  pull_request:
  schedule:
    - cron: '55 23 * * 0'

jobs:
  setup-download-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Reset download branch based on emptyrepo branch
        run: |
          git clone -b emptyrepo https://x-access-token:${{secrets.github_token}}@github.com/${{github.repository}}.git emptyrepo
          git checkout -B download emptyrepotag
          git push --set-upstream origin download
  produce-slides:
    needs: setup-download-repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ essentials, full ]
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup essentials course
        if: matrix.version == 'essentials'
        run: echo '\setboolean{onlybasics}{true}' > talk/onlybasics.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: C++Course.tex
          latexmk_use_xelatex: true
          args: -f -pdf -interaction=nonstopmode -shell-escape
          working_directory: talk
          extra_system_packages: "py-pygments"
      - name: Clone download
        run: |
          git clone -b download https://x-access-token:${{secrets.github_token}}@github.com/${{github.repository}}.git download
      - name: Commit to repository
        run: |
          set -x
          mkdir -p download/talk
          cp talk/C++Course.pdf "download/talk/C++Course_${{ matrix.version }}.pdf"
          cd download
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -f "talk/C++Course_${{ matrix.version }}.pdf"
          if (git diff --quiet) || (git diff --staged --quiet)
          then
            git commit -m "Update C++Course_${{ matrix.version }}.pdf"
            git push origin download
          else
            echo "No changes to commit"
          fi
          git push
