name: Produce a stable download link for the slides
on: [push]

jobs:
  produce-slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clone download-slides
        run: |
          git clone -b download-slides https://x-access-token:${{secrets.github_token}}@github.com/${{github.repository}}.git download-slides
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: C++Course.tex
          latexmk_use_xelatex: true
          args: -f -pdf -interaction=nonstopmode -shell-escape
          working_directory: download-slides/talk
          extra_system_packages: "py-pygments"
      - name: Commit to repo
        run: |
          set -x
          cd download-slides
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -f talk/C++Course.pdf
          if (git diff --quiet) || (git diff --staged --quiet)
          then
            git commit -m "Update C++Course.pdf"
            git push origin download-slides
          else
            echo "No changes to commit"
          fi
          git push
